---
image: archlinux
packages:
  - python
  - python-pip
sources:
  - https://git.sr.ht/~jmcantrell/swaystatus
tasks:
  - setup: |
      cd swaystatus
      python -m venv venv
      . ./venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements/production.txt -r requirements/development.txt
      pip install -e .
  - test: |
      cd swaystatus
      . ./venv/bin/activate
      pytest
