---
image: archlinux
packages:
  - uv
sources:
  - https://git.sr.ht/~jmcantrell/swaystatus
tasks:
  - setup: |
      cd swaystatus
      uv sync --frozen
  - lint-commits: |
      cd swaystatus
      uvx --from gitlint-core gitlint --ignore-stdin --commits "origin/main..HEAD"
  - test: |
      cd swaystatus
      uv run --frozen python -m unittest discover -s ./tests
