from functools import cached_property
from itertools import chain
from json import JSONEncoder
from signal import SIGCONT, SIGSTOP
from typing import IO, Any, Iterable, Iterator

from .block import Block
from .element import BaseElement


class OutputProcessor:
    """Assemble blocks generated by elements into a status line."""

    def __init__(self, elements: Iterable[BaseElement], click_events=False) -> None:
        self.elements = list(elements)
        self.click_events = bool(click_events)

    @cached_property
    def header(self) -> dict[str, Any]:
        return dict(
            version=1,
            stop_signal=SIGSTOP,
            cont_signal=SIGCONT,
            click_events=self.click_events,
        )

    def process(self, file: IO[str]) -> Iterator[list[Block]]:
        """Send status lines to output and yield the originating blocks."""

        def send(line: str) -> None:
            print(line, file=file, flush=True)

        encoder = Encoder()
        send(encoder.encode(self.header))
        send("[[]")
        while True:
            blocks = list(status_line(self.elements))
            send(",{}".format(encoder.encode(blocks)))
            yield blocks


def status_line(elements: Iterable[BaseElement]) -> Iterator[Block]:
    return chain.from_iterable(element.blocks() for element in elements)


class Encoder(JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Block):
            return obj.as_dict()
        return super().default(obj)


__all__ = [OutputProcessor.__name__]
