#!/usr/bin/env bash

set -euo pipefail

data_file=./.coverage

if [[ ! -f $data_file ]] || ! find . -type f -newer "$data_file" -exec false {} + -quit; then
    uv run coverage run -m unittest discover -q -s ./tests
fi

uv run coverage report "$@" --data-file="$data_file" --
