#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

version=${1:?missing version}
version=v${version##v}

sed -i "/^version[[:space:]]=/s/=.*/= \"${version##v}\"/" ./pyproject.toml
git add ./pyproject.toml

sed -i "/^__version__[[:space:]]=/s/=.*/= \"$version\"/" ./src/*/__init__.py
git add ./src/*/__init__.py

git commit -m "Bump version"
git tag "$version"
