#!/usr/bin/env bash

set -euo pipefail

unset bump

while getopts "Mmp" opt; do
    case $opt in
    M) bump='major' ;;
    m) bump='minor' ;;
    p) bump='patch' ;;
    *) exit 2 ;;
    esac
done
shift $((OPTIND - 1))

name=$(uv version | cut -d' ' -f1)
file=./src/$name/version

if [[ -v bump ]]; then
    uv version --bump "$bump"
fi

version=$(uv version --short)
printf "%s\n" "$version" >"$file"

if [[ -v bump ]]; then
    git add "$file" uv.lock pyproject.toml
    git commit -m "Bump $bump version"
    git tag "v$version"
fi
