#!/usr/bin/env sh

set -eu

version=${1:?missing version}
version=${version##v}

sed -i "/^version[[:space:]]=/s/=.*/= \"$version\"/" ./pyproject.toml
git add ./pyproject.toml

sed -i "/^__version__[[:space:]]=/s/=.*/= \"$version\"/" ./src/*/__init__.py
git add ./src/*/__init__.py

uv sync
git add uv.lock

git commit -m "Bump version"
git tag "v$version"
