name: 'Run tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create venv
        run: |
          python -m venv venv

      - name: Install dependencies
        run: |
          . ./venv/bin/activate
          pip install --upgrade pip
          pip install --requirement=requirements/{production,development}.txt
          pip install --editable=.

      - name: Execute test runner
        run: |
          . ./venv/bin/activate
          ./scripts/test
